---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-root-auth
type: kubernetes.io/basic-auth
stringData:
  username: root
  password: password # Replace with your password
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
  - port: 3306
    name: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.6
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-root-auth
              key: password
        - name: MYSQL_DATABASE
          value: mlflow # Automatically create db named 'mlflow'
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql
        persistentVolumeClaim:
          claimName: mysql
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mlflow-artifact
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow
spec:
  type: NodePort
  selector:
    app: mlflow
  ports:
  - protocol: TCP
    port: 5000
    nodePort: 30050
    targetPort: 5000
    name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  labels:
    app: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      volumes:
      - name: mlflow-artifact
        persistentVolumeClaim:
          claimName: mlflow-artifact
      containers:
      - name: mlflow
        image: mboglesby/mlflow:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-root-auth
              key: password
        command: ["mlflow", "server"]
        args:
        - "--backend-store-uri"
        - "mysql://root:$(MYSQL_ROOT_PASSWORD)@$(MYSQL_SERVICE_HOST):$(MYSQL_SERVICE_PORT)/mlflow"
        - "--default-artifact-root"
        - "file:///mnt/mlflow-artifact"
        - "--host"
        - "0.0.0.0"
        ports:
        - containerPort: 5000
          name: http
        volumeMounts:
        - mountPath: "/mnt/mlflow-artifact"
          name: mlflow-artifact
