---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mlflow-backend
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mlflow-artifact
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  labels:
    app: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      volumes:
      - name: mlflow-backend
        persistentVolumeClaim:
          claimName: mlflow-backend
      - name: mlflow-artifact
        persistentVolumeClaim:
          claimName: mlflow-artifact
      containers:
      - name: mlflow
        image: mboglesby/mlflow:latest
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: "/mnt/mlflow-backend"
          name: mlflow-backend
        - mountPath: "/mnt/mlflow-artifact"
          name: mlflow-artifact
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow
spec:
  type: NodePort
  selector:
    app: mlflow
  ports:
  - protocol: TCP
    port: 5000
    nodePort: 30050
    targetPort: 5000
    name: http
